<i class="fa fa-arrow-circle-down" aria-hidden="true"> 请在下方代码块中开始编写代码！</i>

In [4]:
import numpy as np

a = np.array([1, 2, 3, 4], dtype='float')
a, a.dtype

(array([1., 2., 3., 4.]), dtype('float64'))

In [5]:
b = a.astype(int)
b, b.dtype

(array([1, 2, 3, 4]), dtype('int64'))

In [14]:
a.shape, a.buffer

AttributeError: 'numpy.ndarray' object has no attribute 'buffer'

In [7]:
np.array([[1,2,3],[4,5,6]], order='C', ndmin=5)

array([[[[[1, 2, 3],
          [4, 5, 6]]]]])

In [8]:
np.arange(3,7,0.5,dtype='float').dtype

dtype('float64')

In [9]:
np.linspace(0, 10, 5, endpoint=True)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [10]:
np.linspace(0, 10, 5, endpoint=False)

array([0., 2., 4., 6., 8.])

In [11]:
np.ones(3, order='F')

array([1., 1., 1.])

In [12]:
np.eye(5, 4, -2)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [15]:
np.frombuffer()

TypeError: frombuffer() missing required argument 'buffer' (pos 1)

In [16]:
np.fromfunction(lambda a, b: a+b, (5, 4))

array([[0., 1., 2., 3.],
       [1., 2., 3., 4.],
       [2., 3., 4., 5.],
       [3., 4., 5., 6.],
       [4., 5., 6., 7.]])

In [17]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a  # 查看 a 的值

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
a.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [19]:
a.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [20]:
a.imag

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [21]:
a.real

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
a.size

9

In [23]:
a.itemsize

8

In [24]:
a.nbytes

72

In [25]:
a.ndim

2

In [26]:
a.shape

(3, 3)

In [27]:
a.strides

(24, 8)

In [28]:
np.arange(10).reshape((-1, 2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [29]:
a = np.arange(10).reshape((-1, 2))
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [30]:
np.ravel(a)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
np.ravel(a, order='F')

array([0, 2, 4, 6, 8, 1, 3, 5, 7, 9])

In [32]:
a = np.ones((1, 2, 3))

a, np.moveaxis(a, 0, -1)

(array([[[1., 1., 1.],
         [1., 1., 1.]]]),
 array([[[1.],
         [1.],
         [1.]],
 
        [[1.],
         [1.],
         [1.]]]))

In [33]:
a.shape, np.moveaxis(a, 0, -1).shape

((1, 2, 3), (2, 3, 1))

In [34]:
a = np.ones((2, 4, 3))
a, np.swapaxes(a, 0, 2)

(array([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],
 
        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]]),
 array([[[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],
 
        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],
 
        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]]]))

In [35]:
a = np.ones((1, 4, 3))
b = np.swapaxes(a, 0, 2)

In [40]:
a = np.arange(4).reshape(2, 2)
b = np.transpose(a)
a, b

(array([[0, 1],
        [2, 3]]),
 array([[0, 2],
        [1, 3]]))

In [41]:
print(np.atleast_1d([1, 2, 3]))
print(np.atleast_2d([4, 5, 6]))
print(np.atleast_3d([7, 8, 9]))

[1 2 3]
[[4 5 6]]
[[[7]
  [8]
  [9]]]


In [42]:
a = np.arange(4).reshape(2, 2)
np.asmatrix(a)  # 将二维数组转化为矩阵类型

matrix([[0, 1],
        [2, 3]])

In [46]:
a = np.array([[1, 2], [3, 4], [5, 6]])
b = np.array([[7, 8], [9, 10]])
c = np.array([[11, 12]])

np.concatenate((a, b, c), axis=0)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [45]:
a = np.array([[1, 2], [3, 4], [5, 6]])
b = np.array([[7, 8, 9]])

np.concatenate((a, b.T), axis=1)

array([[1, 2, 7],
       [3, 4, 8],
       [5, 6, 9]])